spring:
  datasource:
    url: jdbc:mysql://localhost:13308/hop
    username: mariadb
    password: mariadb
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    initialize-schema: never
  main:
    allow-bean-definition-overriding: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    org.springframework.boot.web.servlet.ServletContextInitializerBeans: trace