version: '3.1'
services:
  mysql:
    build: ./
    image: spring-batch-example-app/mariadb:1
    command: mysqld --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    container_name: spring-batch-example-app
    ports:
    - "13320:3306"
    environment:
    - MYSQL_DATABASE=hop
    - MYSQL_USER=mariadb
    - MYSQL_PASSWORD=mariadb
    - MYSQL_ROOT_PASSWORD=root
